name: minoic-auto-catalog

on:
  push:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: minoic/markdown-auto-catalog@v1.0.0
      with:
        content-path: '/test/folder/'
        document-path: '/test/README.md'
      continue-on-error: true
